### ISSUE TITLE
Callbacks in cash and bond test cases

### ISSUE THREAD

**Issue by kallolborah** [verified-network/verified-payments#49]
Callbacks from the oracle are timing out in the test cases. 

Posted the issue here https://github.com/rkalis/truffle-assertions/issues/35

I have set mocha timeout in truffle config but it has no effect.

**Comment by kallolborah** [comment]
Here are the test results for Cash with oracle bypassed today (#103 travis). We should see similar results with oracle callbacks. 

---------------------------
  Contract: CashContractSize
size of bytecode in bytes =  19472
size of deployed in bytes =  19453
initialisation and constructor code in bytes =  19
    ✓ get the size of the Cash contract (320ms)
    > No events were emitted
  Contract: IssuingViaUSD
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367611960000000000
Account Via-USD cash token balance before sending ether: 0
Via oracle ether balance before query: 250000000000000000
Via-USD cash token contract ether balance after sending ether: 1000000000000000000
Account ether balance after sending ether: 98362065280000000000
Via oracle ether balance after query: 250000000000000000
Account Via-USD cash token balance after sending ether: 45125
    ✓ should send ether to Via-USD cash contract and then get some Via-USD cash tokens (2157ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669615f55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: IssuingViaEUR
Via_EUR ViaCash token address: 0xFB4B8C5139910f2F601780bFb3bF433b1d963e0c
Via_EUR ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367311960000000000
Account Via-EUR cash token balance before sending ether: 0
Via oracle ether balance before query: 250000000000000000
Via-EUR cash token contract ether balance after sending ether: 1000000000000000000
Account ether balance after sending ether: 98361474000000000000
Via oracle ether balance after query: 250000000000000000
Account Via-EUR cash token balance after sending ether: 541500
    ✓ should send ether to Via-EUR cash contract and then get some Via-EUR cash tokens (1861ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d45555200000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: ViaUSDExchange
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Via_EUR ViaCash token address: 0xFB4B8C5139910f2F601780bFb3bF433b1d963e0c
Via_EUR ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367311960000000000
Account Via-USD cash token balance before sending ether: 0
Account Via-EUR cash token balance before sending ether: 0
Via oracle ether balance before query: 250000000000000000
Via oracle ether balance after query: 250000000000000000
Via-USD cash token contract ether balance after sending ether and before sending Via-USD: 1000000000000000000
Via-EUR cash token contract ether balance after sending ether and before sending Via-USD: 0
Account ether balance after sending ether and before sending Via-USD: 98361765280000000000
Account Via-USD cash token balance after sending ether and before sending Via-USD: 45125
Account Via-EUR cash token balance after sending ether and before sending Via-USD: 0
Via oracle ether balance before query: 250000000000000000
Via oracle ether balance after query: 250000000000000000
Via-USD cash token contract ether balance after sending Via-USD: 1000000000000000000
Via-EUR cash token contract ether balance after sending Via-USD: 0
Account ether balance after sending Via-USD: 98356103380000000000
Account Via-USD cash token balance after sending Via-USD: 45115
Account Via-EUR cash token balance after sending Via-USD: 760
    ✓ should send Via-USD to Via-EUR cash contract and then get some Via-EUR cash tokens (2032ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: ViaUSDRedemption
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367611960000000000
Account Via-USD cash token balance before sending ether: 0
Via-USD cash token contract ether balance after sending ether and before sending Via-USD: 1000000000000000000
Account ether balance after sending ether and before sending Via-USD: 98362065280000000000
Account Via-USD cash token balance after sending ether and before sending Via-USD: 45125
Via-USD cash token contract ether balance after sending Via-USD: 1000000000000000000
Account ether balance after sending Via-USD: 98357678620000000000
Account Via-USD cash token balance after sending Via-USD: 45115
    ✓ should send Via-USD to Via-USD cash contract and then get ether sent during issuing process (1999ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669615f55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: ViaEURRedemption
Via_EUR ViaCash token address: 0xFB4B8C5139910f2F601780bFb3bF433b1d963e0c
Via_EUR ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367311960000000000
Account Via-EUR cash token balance before sending ether: 0
Via-EUR cash token contract ether balance after sending ether: 1000000000000000000
Account ether balance after sending ether: 98361474000000000000
Account Via-EUR cash token balance after sending ether: 541500
Via-EUR cash token contract ether balance after sending Via-EUR: 1000000000000000000
Account ether balance after sending Via-EUR: 98356880520000000000
Account Via-EUR cash token balance after sending Via-EUR: 541490
    ✓ should send Via-EUR tokens to Via-EUR contract and get back ether paid in earlier (2029ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d45555200000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: ViaUSDRedemptionAfterTransfer
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Sender address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Sender ether balance before sending ether: 99367311960000000000
Sender Via-USD cash token balance before sending ether: 0
Via-USD cash token contract ether balance after sending ether: 1000000000000000000
Account ether balance after sending ether: 98361765280000000000
Sender Via-USD cash token balance after sending ether and before sending Via-USD: 45125
Receiver address: 0x0eaEdD541c97de4dfd1b2759fe54F74AEa12b68e
Receiver ether balance before Via-USD is sent by sender: 100000000000000000000
Receiver Via-USD cash token balance before receiving Via-USD: 0
Sender ether balance after sending Via-USD: 98356519520000000000
Sender Via-USD cash token balance after sending Via-USD: 45025
Receiver ether balance after Via-USD is sent by sender: 100000000000000000000
Receiver Via-USD cash token balance after receiving Via-USD: 100
Via-USD cash token contract ether balance after redeeming Via-USD: 1000000000000000000
Account ether balance after redeeming Via-USD: 100000000000000000000
Account Via-USD cash token balance after redeeming Via-USD: 50
    ✓ should send Via-USD tokens to Via-USD contract after transfer of Via-USD tokens from one user account to another (2132ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: TransferViaUSD
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Sender address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Sender ether balance before sending ether: 99367311960000000000
Sender Via-USD cash token balance before sending ether: 0
Via-USD cash token contract ether balance after sending ether: 1000000000000000000
Account ether balance after sending ether: 98361765280000000000
Sender Via-USD cash token balance after sending ether and before sending Via-USD: 45125
Receiver address: 0x0eaEdD541c97de4dfd1b2759fe54F74AEa12b68e
Receiver ether balance before Via-USD is sent by sender: 100000000000000000000
Receiver Via-USD cash token balance before receiving Via-USD: 0
Sender ether balance after sending Via-USD: 98356519520000000000
Sender Via-USD cash token balance after sending Via-USD: 45025
Receiver ether balance after Via-USD is sent by sender: 100000000000000000000
Receiver Via-USD cash token balance after receiving Via-USD: 100
    ✓ should transfer Via-USD to another account (2194ms)
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  Contract: ViaUSDRedemptionAfterEURExchangeTransferAndRedemption
Via_USD ViaCash token address: 0x377dc73537569095991DbdD712F21Fb8930D6856
Via_USD ViaCash token contract ether balance before sending ether: 0
Via_EUR ViaCash token address: 0xFB4B8C5139910f2F601780bFb3bF433b1d963e0c
Via_EUR ViaCash token contract ether balance before sending ether: 0
Account address: 0x988dEFBD2BC836e0482AB1c997F3145b4E4120EB
Account ether balance before sending ether: 99367311960000000000
Account Via-USD cash token balance before sending ether: 0
Account Via-EUR cash token balance before sending ether: 0
Via-USD cash token contract ether balance after sending ether and before sending Via-USD: 1000000000000000000
Via-EUR cash token contract ether balance after sending ether and before sending Via-USD: 0
Account ether balance after sending ether and before sending Via-USD: 98361765280000000000
Account Via-USD cash token balance after sending ether and before sending Via-USD: 45125
Account Via-EUR cash token balance after sending ether and before sending Via-USD: 0
Via-USD cash token contract ether balance after sending Via-USD: 1000000000000000000
Via-EUR cash token contract ether balance after sending Via-USD: 0
Account ether balance after sending Via-USD: 98356101300000000000
Account Via-USD cash token balance after sending Via-USD: 45025
Account Via-EUR cash token balance after sending Via-USD: 7600
Sender ether balance after transferring Via-EUR: 98350390600000000000
Sender Via-EUR cash token balance after transferring Via-EUR: 7550
Receiver ether balance after Via-EUR is transferred by sender: 100000000000000000000
Receiver Via-EUR cash token balance after transfer of Via-EUR: 50
    1) should send Via-USD to Via-EUR cash contract, get some Via-EUR cash tokens which it should transfer to another account which will redeem Via-EUR to get Via-USD which it will again redeem to get ether
    Events emitted during test:
    ---------------------------
    ProxyFactory.ProxyCreated(
      proxy: 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address)
    )
    Warning: Could not decode event!
    Factory.IssuerCreated(
      _address: <indexed> 0xbdDEDe331605f9014FA826dda8E45e47E9Da6519 (type: address),
      tokenName: 0x5669612d55534400000000000000000000000000000000000000000000000000 (type: bytes32),
      tokenType: 0x4361736800000000000000000000000000000000000000000000000000000000 (type: bytes32)
    )
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    Warning: Could not decode event!
    ---------------------------
  17 passing (50s)
  1 failing
  1) Contract: ViaUSDRedemptionAfterEURExchangeTransferAndRedemption
       should send Via-USD to Via-EUR cash contract, get some Via-EUR cash tokens which it should transfer to another account which will redeem Via-EUR to get Via-USD which it will again redeem to get ether:
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (test/ViaCash.js:464:22)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by kallolborah** [comment]
@bonedaddy all bond tests are also passing in oracle branch but since bonds create bond tokens in each test case, I am still unable to get the bond token address in each test bondjs test case. I am using truffleAssert.eventEmitted in each test case to capture the event. This is preventing me from testing all the bondjs cases

**Comment by kallolborah** [comment]
Fixed callbacks in both cash and bond tests
